#!/bin/bash
# TODO PORT
service=$1
echo "!!! got service $command" >> /home/reddit/log.log
command=${UPSTART_JOB#reddit-consumers-}
for consumerpath in $REDDIT_CONSUMER_CONFIG/*; do
    consumer=$(basename $consumerpath)

    # allow targeting which consumer the event is meant for (defaulting to 'all')
    if [ ! -z "$TARGET" -a "x$TARGET" != "xall" -a "x$TARGET" != "x$consumer" ]; then
        continue
    fi

    if [ -d $consumerpath ]; then
        types=$consumerpath/*
    else
        types=$consumerpath
    fi

    for typepath in $types; do
        instance_count=$(cat $typepath)
        type_=$(basename $typepath)

        for i in $(seq 1 "$instance_count"); do
            # command: start, stop, or restart
            # consumer:
            # type: consumer name like author_query_q, butler_q, scraper_q
            # "/sbin/$command" "reddit-consumer-$consumer" "type=$type_" "x=$i"
            echo "!!! type is $type_" >> /home/reddit/log.log
            echo "!!! running systemctl start $service@$i" >> /home/reddit/log.log
            "systemctl start" "$service@$i"
        done
    done
done

